<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.29.0/feather.min.js"></script>
<script src="{{ asset('dashboard/assets/js/icons/feather-icon/feather-icon.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/simplebar/5.3.0/simplebar.min.js"></script>
<script src="{{ asset('dashboard/assets/js/scrollbar/custom.js') }}"></script>
<script src="{{ asset('dashboard/assets/js/config.js') }}"></script>
<script src="{{ asset('dashboard/assets/js/sidebar-menu.js') }}"></script>
<script src="{{ asset('dashboard/assets/js/sidebar-pin.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></script>
<script src="{{ asset('dashboard/assets/js/header-slick.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/apexcharts/3.36.2/apexcharts.min.js"></script>
<script src="{{ asset('dashboard/assets/js/chart/apex-chart/stock-prices.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.4/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="{{ asset('dashboard/assets/js/datatable/datatables/datatable.custom.js') }}"></script>
<script src="{{ asset('dashboard/assets/js/datatable/datatables/datatable.custom1.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.10.5/sweetalert2.all.min.js"></script>
<script src="{{ asset('dashboard/assets/js/dashboard/dashboard_4.js') }}"></script>
<script src="{{ asset('dashboard/assets/js/script.js') }}"></script>
<script src="{{ asset('dashboard/assets/js/script1.js') }}"></script>