<?php

namespace Database\Seeders\Menu;

use App\Models\InventoryItems;
use Illuminate\Database\Seeder;

class InventoryItemsSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            // ── Proteins ───────────────────────────────────────────────────
            ['name' => 'Beef Patty',            'unit' => 'g',    'current_stock' => 10000, 'minimum_stock' => 2000, 'status' => 1],
            ['name' => 'Chicken Breast',         'unit' => 'g',    'current_stock' => 8000,  'minimum_stock' => 1500, 'status' => 1],
            ['name' => 'Bacon Strips',           'unit' => 'g',    'current_stock' => 5000,  'minimum_stock' => 1000, 'status' => 1],
            ['name' => 'Pepperoni',              'unit' => 'g',    'current_stock' => 4000,  'minimum_stock' => 800,  'status' => 1],
            ['name' => 'Tuna (canned)',          'unit' => 'g',    'current_stock' => 3000,  'minimum_stock' => 500,  'status' => 1],
            ['name' => 'Salmon Fillet',          'unit' => 'g',    'current_stock' => 4000,  'minimum_stock' => 800,  'status' => 1],
            ['name' => 'Prawns',                 'unit' => 'g',    'current_stock' => 3000,  'minimum_stock' => 600,  'status' => 1],
            ['name' => 'Lamb Chops',             'unit' => 'g',    'current_stock' => 5000,  'minimum_stock' => 1000, 'status' => 1],
            ['name' => 'Pork Ribs',              'unit' => 'g',    'current_stock' => 6000,  'minimum_stock' => 1200, 'status' => 1],
            ['name' => 'Ribeye Steak',           'unit' => 'g',    'current_stock' => 6000,  'minimum_stock' => 1200, 'status' => 1],
            ['name' => 'T-Bone Steak',           'unit' => 'g',    'current_stock' => 5000,  'minimum_stock' => 1000, 'status' => 1],
            ['name' => 'Minced Beef',            'unit' => 'g',    'current_stock' => 8000,  'minimum_stock' => 1500, 'status' => 1],
            ['name' => 'Pancetta',               'unit' => 'g',    'current_stock' => 2000,  'minimum_stock' => 400,  'status' => 1],
            ['name' => 'Fish Fillet',            'unit' => 'g',    'current_stock' => 3000,  'minimum_stock' => 600,  'status' => 1],
            ['name' => 'Pulled Pork',            'unit' => 'g',    'current_stock' => 4000,  'minimum_stock' => 800,  'status' => 1],
            ['name' => 'Squid',                  'unit' => 'g',    'current_stock' => 2000,  'minimum_stock' => 400,  'status' => 1],
            ['name' => 'Mussels',                'unit' => 'g',    'current_stock' => 2000,  'minimum_stock' => 400,  'status' => 1],
            ['name' => 'Ham',                    'unit' => 'g',    'current_stock' => 3000,  'minimum_stock' => 600,  'status' => 1],
            ['name' => 'Wagyu Beef',             'unit' => 'g',    'current_stock' => 2000,  'minimum_stock' => 400,  'status' => 1],
            ['name' => 'Sausage',                'unit' => 'g',    'current_stock' => 3000,  'minimum_stock' => 600,  'status' => 1],

            // ── Dairy ──────────────────────────────────────────────────────
            ['name' => 'Cheddar Cheese',         'unit' => 'g',    'current_stock' => 5000,  'minimum_stock' => 1000, 'status' => 1],
            ['name' => 'Mozzarella',             'unit' => 'g',    'current_stock' => 6000,  'minimum_stock' => 1200, 'status' => 1],
            ['name' => 'Parmesan',               'unit' => 'g',    'current_stock' => 3000,  'minimum_stock' => 500,  'status' => 1],
            ['name' => 'Swiss Cheese',           'unit' => 'g',    'current_stock' => 2000,  'minimum_stock' => 400,  'status' => 1],
            ['name' => 'Gorgonzola',             'unit' => 'g',    'current_stock' => 1000,  'minimum_stock' => 200,  'status' => 1],
            ['name' => 'Feta Cheese',            'unit' => 'g',    'current_stock' => 2000,  'minimum_stock' => 400,  'status' => 1],
            ['name' => 'Mascarpone',             'unit' => 'g',    'current_stock' => 2000,  'minimum_stock' => 400,  'status' => 1],
            ['name' => 'Butter',                 'unit' => 'g',    'current_stock' => 5000,  'minimum_stock' => 1000, 'status' => 1],
            ['name' => 'Milk',                   'unit' => 'ml',   'current_stock' => 10000, 'minimum_stock' => 2000, 'status' => 1],
            ['name' => 'Cream',                  'unit' => 'ml',   'current_stock' => 5000,  'minimum_stock' => 1000, 'status' => 1],
            ['name' => 'Egg',                    'unit' => 'pcs',  'current_stock' => 200,   'minimum_stock' => 40,   'status' => 1],
            ['name' => 'Yoghurt',                'unit' => 'g',    'current_stock' => 3000,  'minimum_stock' => 600,  'status' => 1],
            ['name' => 'Gruyère',                'unit' => 'g',    'current_stock' => 1500,  'minimum_stock' => 300,  'status' => 1],

            // ── Bread / Grains ─────────────────────────────────────────────
            ['name' => 'Burger Bun',             'unit' => 'pcs',  'current_stock' => 300,   'minimum_stock' => 60,   'status' => 1],
            ['name' => 'Sourdough Bread',        'unit' => 'slices','current_stock'=> 400,   'minimum_stock' => 80,   'status' => 1],
            ['name' => 'Hoagie Roll',            'unit' => 'pcs',  'current_stock' => 100,   'minimum_stock' => 20,   'status' => 1],
            ['name' => 'Flour Tortilla',         'unit' => 'pcs',  'current_stock' => 200,   'minimum_stock' => 40,   'status' => 1],
            ['name' => 'Flatbread',              'unit' => 'pcs',  'current_stock' => 150,   'minimum_stock' => 30,   'status' => 1],
            ['name' => 'Pizza Dough',            'unit' => 'g',    'current_stock' => 10000, 'minimum_stock' => 2000, 'status' => 1],
            ['name' => 'Spaghetti',              'unit' => 'g',    'current_stock' => 8000,  'minimum_stock' => 1500, 'status' => 1],
            ['name' => 'Penne',                  'unit' => 'g',    'current_stock' => 8000,  'minimum_stock' => 1500, 'status' => 1],
            ['name' => 'Fettuccine',             'unit' => 'g',    'current_stock' => 5000,  'minimum_stock' => 1000, 'status' => 1],
            ['name' => 'Lasagna Sheets',         'unit' => 'g',    'current_stock' => 5000,  'minimum_stock' => 1000, 'status' => 1],
            ['name' => 'Linguine',               'unit' => 'g',    'current_stock' => 5000,  'minimum_stock' => 1000, 'status' => 1],
            ['name' => 'Potato Gnocchi',         'unit' => 'g',    'current_stock' => 4000,  'minimum_stock' => 800,  'status' => 1],
            ['name' => 'Arborio Rice',           'unit' => 'g',    'current_stock' => 4000,  'minimum_stock' => 800,  'status' => 1],
            ['name' => 'Egg Noodles',            'unit' => 'g',    'current_stock' => 4000,  'minimum_stock' => 800,  'status' => 1],
            ['name' => 'Ladyfingers',            'unit' => 'g',    'current_stock' => 2000,  'minimum_stock' => 400,  'status' => 1],
            ['name' => 'Waffle Mix',             'unit' => 'g',    'current_stock' => 3000,  'minimum_stock' => 600,  'status' => 1],
            ['name' => 'Croutons',               'unit' => 'g',    'current_stock' => 2000,  'minimum_stock' => 400,  'status' => 1],
            ['name' => 'Oats',                   'unit' => 'g',    'current_stock' => 3000,  'minimum_stock' => 600,  'status' => 1],
            ['name' => 'White Bread',            'unit' => 'slices','current_stock'=> 300,   'minimum_stock' => 60,   'status' => 1],
            ['name' => 'Panini Bread',           'unit' => 'pcs',  'current_stock' => 100,   'minimum_stock' => 20,   'status' => 1],

            // ── Vegetables / Fruits ────────────────────────────────────────
            ['name' => 'Tomato',                 'unit' => 'g',    'current_stock' => 8000,  'minimum_stock' => 1500, 'status' => 1],
            ['name' => 'Lettuce',                'unit' => 'g',    'current_stock' => 5000,  'minimum_stock' => 1000, 'status' => 1],
            ['name' => 'Cucumber',               'unit' => 'g',    'current_stock' => 4000,  'minimum_stock' => 800,  'status' => 1],
            ['name' => 'Avocado',                'unit' => 'pcs',  'current_stock' => 100,   'minimum_stock' => 20,   'status' => 1],
            ['name' => 'Bell Pepper',            'unit' => 'g',    'current_stock' => 4000,  'minimum_stock' => 800,  'status' => 1],
            ['name' => 'Mushrooms',              'unit' => 'g',    'current_stock' => 4000,  'minimum_stock' => 800,  'status' => 1],
            ['name' => 'Onion',                  'unit' => 'g',    'current_stock' => 6000,  'minimum_stock' => 1200, 'status' => 1],
            ['name' => 'Garlic',                 'unit' => 'g',    'current_stock' => 3000,  'minimum_stock' => 500,  'status' => 1],
            ['name' => 'Jalapeño',               'unit' => 'g',    'current_stock' => 1000,  'minimum_stock' => 200,  'status' => 1],
            ['name' => 'Corn',                   'unit' => 'g',    'current_stock' => 3000,  'minimum_stock' => 600,  'status' => 1],
            ['name' => 'Broccoli',               'unit' => 'g',    'current_stock' => 3000,  'minimum_stock' => 600,  'status' => 1],
            ['name' => 'Pumpkin',                'unit' => 'g',    'current_stock' => 4000,  'minimum_stock' => 800,  'status' => 1],
            ['name' => 'Lentils',                'unit' => 'g',    'current_stock' => 4000,  'minimum_stock' => 800,  'status' => 1],
            ['name' => 'Chickpeas',              'unit' => 'g',    'current_stock' => 3000,  'minimum_stock' => 600,  'status' => 1],
            ['name' => 'Olives',                 'unit' => 'g',    'current_stock' => 2000,  'minimum_stock' => 400,  'status' => 1],
            ['name' => 'Capers',                 'unit' => 'g',    'current_stock' => 1000,  'minimum_stock' => 200,  'status' => 1],
            ['name' => 'Asparagus',              'unit' => 'g',    'current_stock' => 2000,  'minimum_stock' => 400,  'status' => 1],
            ['name' => 'Green Beans',            'unit' => 'g',    'current_stock' => 2000,  'minimum_stock' => 400,  'status' => 1],
            ['name' => 'Apple',                  'unit' => 'g',    'current_stock' => 3000,  'minimum_stock' => 600,  'status' => 1],
            ['name' => 'Mango',                  'unit' => 'g',    'current_stock' => 2000,  'minimum_stock' => 400,  'status' => 1],
            ['name' => 'Strawberry',             'unit' => 'g',    'current_stock' => 3000,  'minimum_stock' => 600,  'status' => 1],
            ['name' => 'Pineapple',              'unit' => 'g',    'current_stock' => 2000,  'minimum_stock' => 400,  'status' => 1],
            ['name' => 'Lemon',                  'unit' => 'pcs',  'current_stock' => 100,   'minimum_stock' => 20,   'status' => 1],
            ['name' => 'Lime',                   'unit' => 'pcs',  'current_stock' => 100,   'minimum_stock' => 20,   'status' => 1],
            ['name' => 'Orange',                 'unit' => 'pcs',  'current_stock' => 100,   'minimum_stock' => 20,   'status' => 1],
            ['name' => 'Watermelon',             'unit' => 'g',    'current_stock' => 6000,  'minimum_stock' => 1200, 'status' => 1],
            ['name' => 'Celery',                 'unit' => 'g',    'current_stock' => 2000,  'minimum_stock' => 400,  'status' => 1],
            ['name' => 'Grapes',                 'unit' => 'g',    'current_stock' => 2000,  'minimum_stock' => 400,  'status' => 1],
            ['name' => 'Rocket (Arugula)',        'unit' => 'g',    'current_stock' => 2000,  'minimum_stock' => 400,  'status' => 1],
            ['name' => 'Romaine Lettuce',        'unit' => 'g',    'current_stock' => 4000,  'minimum_stock' => 800,  'status' => 1],
            ['name' => 'Sun-Dried Tomatoes',     'unit' => 'g',    'current_stock' => 1500,  'minimum_stock' => 300,  'status' => 1],
            ['name' => 'Quinoa',                 'unit' => 'g',    'current_stock' => 3000,  'minimum_stock' => 600,  'status' => 1],
            ['name' => 'Cabbage',                'unit' => 'g',    'current_stock' => 4000,  'minimum_stock' => 800,  'status' => 1],
            ['name' => 'Carrot',                 'unit' => 'g',    'current_stock' => 4000,  'minimum_stock' => 800,  'status' => 1],
            ['name' => 'Chilli',                 'unit' => 'g',    'current_stock' => 1000,  'minimum_stock' => 200,  'status' => 1],
            ['name' => 'Walnut',                 'unit' => 'g',    'current_stock' => 2000,  'minimum_stock' => 400,  'status' => 1],
            ['name' => 'Pine Nuts',              'unit' => 'g',    'current_stock' => 1500,  'minimum_stock' => 300,  'status' => 1],
            ['name' => 'Shallots',               'unit' => 'g',    'current_stock' => 2000,  'minimum_stock' => 400,  'status' => 1],
            ['name' => 'Spring Onion',           'unit' => 'g',    'current_stock' => 2000,  'minimum_stock' => 400,  'status' => 1],

            // ── Sauces / Condiments ────────────────────────────────────────
            ['name' => 'Tomato Sauce',           'unit' => 'ml',   'current_stock' => 10000, 'minimum_stock' => 2000, 'status' => 1],
            ['name' => 'BBQ Sauce',              'unit' => 'ml',   'current_stock' => 5000,  'minimum_stock' => 1000, 'status' => 1],
            ['name' => 'Mayonnaise',             'unit' => 'ml',   'current_stock' => 5000,  'minimum_stock' => 1000, 'status' => 1],
            ['name' => 'Sriracha',               'unit' => 'ml',   'current_stock' => 2000,  'minimum_stock' => 400,  'status' => 1],
            ['name' => 'Mustard',                'unit' => 'ml',   'current_stock' => 3000,  'minimum_stock' => 600,  'status' => 1],
            ['name' => 'Tartar Sauce',           'unit' => 'ml',   'current_stock' => 2000,  'minimum_stock' => 400,  'status' => 1],
            ['name' => 'Caesar Dressing',        'unit' => 'ml',   'current_stock' => 3000,  'minimum_stock' => 600,  'status' => 1],
            ['name' => 'Basil Pesto',            'unit' => 'ml',   'current_stock' => 2000,  'minimum_stock' => 400,  'status' => 1],
            ['name' => 'Hummus',                 'unit' => 'g',    'current_stock' => 3000,  'minimum_stock' => 600,  'status' => 1],
            ['name' => 'Olive Oil',              'unit' => 'ml',   'current_stock' => 5000,  'minimum_stock' => 1000, 'status' => 1],
            ['name' => 'Truffle Oil',            'unit' => 'ml',   'current_stock' => 500,   'minimum_stock' => 100,  'status' => 1],
            ['name' => 'White Wine',             'unit' => 'ml',   'current_stock' => 3000,  'minimum_stock' => 600,  'status' => 1],
            ['name' => 'Maple Syrup',            'unit' => 'ml',   'current_stock' => 2000,  'minimum_stock' => 400,  'status' => 1],
            ['name' => 'Honey',                  'unit' => 'ml',   'current_stock' => 2000,  'minimum_stock' => 400,  'status' => 1],
            ['name' => 'Toffee Sauce',           'unit' => 'ml',   'current_stock' => 2000,  'minimum_stock' => 400,  'status' => 1],
            ['name' => 'Chocolate Sauce',        'unit' => 'ml',   'current_stock' => 2000,  'minimum_stock' => 400,  'status' => 1],
            ['name' => 'Tzatziki',               'unit' => 'g',    'current_stock' => 2000,  'minimum_stock' => 400,  'status' => 1],
            ['name' => 'Raspberry Coulis',       'unit' => 'ml',   'current_stock' => 1500,  'minimum_stock' => 300,  'status' => 1],
            ['name' => 'Béchamel Sauce',         'unit' => 'ml',   'current_stock' => 3000,  'minimum_stock' => 600,  'status' => 1],
            ['name' => 'Apple Slaw',             'unit' => 'g',    'current_stock' => 2000,  'minimum_stock' => 400,  'status' => 1],

            // ── Herbs / Spices ─────────────────────────────────────────────
            ['name' => 'Fresh Basil',            'unit' => 'g',    'current_stock' => 1000,  'minimum_stock' => 200,  'status' => 1],
            ['name' => 'Rosemary',               'unit' => 'g',    'current_stock' => 500,   'minimum_stock' => 100,  'status' => 1],
            ['name' => 'Oregano',                'unit' => 'g',    'current_stock' => 500,   'minimum_stock' => 100,  'status' => 1],
            ['name' => 'Mint',                   'unit' => 'g',    'current_stock' => 500,   'minimum_stock' => 100,  'status' => 1],
            ['name' => 'Chilli Flakes',          'unit' => 'g',    'current_stock' => 500,   'minimum_stock' => 100,  'status' => 1],
            ['name' => 'Black Pepper',           'unit' => 'g',    'current_stock' => 1000,  'minimum_stock' => 200,  'status' => 1],
            ['name' => 'Salt',                   'unit' => 'g',    'current_stock' => 5000,  'minimum_stock' => 1000, 'status' => 1],
            ['name' => 'Cumin',                  'unit' => 'g',    'current_stock' => 500,   'minimum_stock' => 100,  'status' => 1],
            ['name' => 'Cardamom',               'unit' => 'g',    'current_stock' => 300,   'minimum_stock' => 50,   'status' => 1],
            ['name' => 'Vanilla Extract',        'unit' => 'ml',   'current_stock' => 500,   'minimum_stock' => 100,  'status' => 1],

            // ── Beverages / Specialty ──────────────────────────────────────
            ['name' => 'Espresso Shot',          'unit' => 'ml',   'current_stock' => 5000,  'minimum_stock' => 1000, 'status' => 1],
            ['name' => 'Steamed Milk',           'unit' => 'ml',   'current_stock' => 10000, 'minimum_stock' => 2000, 'status' => 1],
            ['name' => 'Belgian Chocolate',      'unit' => 'g',    'current_stock' => 3000,  'minimum_stock' => 600,  'status' => 1],
            ['name' => 'Dark Chocolate',         'unit' => 'g',    'current_stock' => 3000,  'minimum_stock' => 600,  'status' => 1],
            ['name' => 'Green Tea Leaves',       'unit' => 'g',    'current_stock' => 1000,  'minimum_stock' => 200,  'status' => 1],
            ['name' => 'Black Tea Leaves',       'unit' => 'g',    'current_stock' => 1000,  'minimum_stock' => 200,  'status' => 1],
            ['name' => 'Chai Spice Mix',         'unit' => 'g',    'current_stock' => 500,   'minimum_stock' => 100,  'status' => 1],
            ['name' => 'Coconut Water',          'unit' => 'ml',   'current_stock' => 5000,  'minimum_stock' => 1000, 'status' => 1],
            ['name' => 'Almond Milk',            'unit' => 'ml',   'current_stock' => 4000,  'minimum_stock' => 800,  'status' => 1],
            ['name' => 'Soda Water',             'unit' => 'ml',   'current_stock' => 5000,  'minimum_stock' => 1000, 'status' => 1],
            ['name' => 'Sugar Syrup',            'unit' => 'ml',   'current_stock' => 3000,  'minimum_stock' => 600,  'status' => 1],
            ['name' => 'Cold Brew Coffee',       'unit' => 'ml',   'current_stock' => 3000,  'minimum_stock' => 600,  'status' => 1],
            ['name' => 'Whipped Cream',          'unit' => 'ml',   'current_stock' => 3000,  'minimum_stock' => 600,  'status' => 1],
            ['name' => 'Vanilla Ice Cream',      'unit' => 'ml',   'current_stock' => 5000,  'minimum_stock' => 1000, 'status' => 1],
            ['name' => 'Ganache',                'unit' => 'g',    'current_stock' => 2000,  'minimum_stock' => 400,  'status' => 1],
            ['name' => 'Coffee (Brewed)',         'unit' => 'ml',   'current_stock' => 5000,  'minimum_stock' => 1000, 'status' => 1],
        ];

        foreach ($items as $item) {
            InventoryItems::firstOrCreate(['name' => $item['name']], $item);
        }
    }
}