<?php

namespace Database\Seeders\Menu;

use App\Models\Menu;
use App\Models\MenuCategory;
use Illuminate\Database\Seeder;

class MenuSeeder extends Seeder
{
    public function run(): void
    {
        $cats = MenuCategory::pluck('id', 'slug');

        $menus = [

            ['title'=>'Classic Beef Burger',      'slug'=>'classic-beef-burger',      'description'=>'Pure beef patty with lettuce, tomato & pickles.',           'image'=>'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop',  'price'=>599,  'rating'=>4,'priority'=>1, 'status'=>1,'menu_category_id'=>$cats['burgers']],
            ['title'=>'Cheese Burger',             'slug'=>'cheese-burger',             'description'=>'Melted cheddar on a juicy beef patty.',                     'image'=>'https://images.unsplash.com/photo-1550547660-d9450f859349?w=400&h=300&fit=crop',  'price'=>649,  'rating'=>5,'priority'=>2, 'status'=>1,'menu_category_id'=>$cats['burgers']],
            ['title'=>'Double Smash Burger',       'slug'=>'double-smash-burger',       'description'=>'Two smashed patties, special sauce, double cheese.',        'image'=>'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=400&h=300&fit=crop',  'price'=>849,  'rating'=>5,'priority'=>3, 'status'=>1,'menu_category_id'=>$cats['burgers']],
            ['title'=>'Crispy Chicken Burger',     'slug'=>'crispy-chicken-burger',     'description'=>'Buttermilk-fried chicken, coleslaw, pickles.',              'image'=>'https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=400&h=300&fit=crop',  'price'=>699,  'rating'=>4,'priority'=>4, 'status'=>1,'menu_category_id'=>$cats['burgers']],
            ['title'=>'Spicy Jalapeño Burger',     'slug'=>'spicy-jalapeno-burger',     'description'=>'Beef patty with jalapeños, pepper jack & sriracha mayo.',   'image'=>'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=400&h=300&fit=crop',  'price'=>749,  'rating'=>4,'priority'=>5, 'status'=>1,'menu_category_id'=>$cats['burgers']],
            ['title'=>'BBQ Bacon Burger',          'slug'=>'bbq-bacon-burger',          'description'=>'Smoky BBQ sauce, crispy bacon, caramelised onions.',        'image'=>'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=400&h=300&fit=crop',  'price'=>799,  'rating'=>5,'priority'=>6, 'status'=>1,'menu_category_id'=>$cats['burgers']],
            ['title'=>'Mushroom Swiss Burger',     'slug'=>'mushroom-swiss-burger',     'description'=>'Sautéed mushrooms and Swiss cheese on a beef patty.',       'image'=>'https://images.unsplash.com/photo-1582196016295-f8c8bd4b3a99?w=400&h=300&fit=crop',  'price'=>749,  'rating'=>4,'priority'=>7, 'status'=>1,'menu_category_id'=>$cats['burgers']],
            ['title'=>'Veggie Bean Burger',        'slug'=>'veggie-bean-burger',        'description'=>'Black bean patty with avocado, lettuce & tomato.',          'image'=>'https://images.unsplash.com/photo-1520072959219-c595dc870360?w=400&h=300&fit=crop',  'price'=>599,  'rating'=>3,'priority'=>8, 'status'=>1,'menu_category_id'=>$cats['burgers']],
            ['title'=>'Truffle Burger',            'slug'=>'truffle-burger',            'description'=>'Wagyu patty with truffle mayo and arugula.',                'image'=>'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&h=300&fit=crop',  'price'=>1099, 'rating'=>5,'priority'=>9, 'status'=>1,'menu_category_id'=>$cats['burgers']],
            ['title'=>'Fish Fillet Burger',        'slug'=>'fish-fillet-burger',        'description'=>'Crispy fish fillet with tartar sauce and lettuce.',         'image'=>'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=400&h=300&fit=crop',  'price'=>649,  'rating'=>3,'priority'=>10,'status'=>1,'menu_category_id'=>$cats['burgers']],

            ['title'=>'Margherita Pizza',          'slug'=>'margherita-pizza',          'description'=>'Classic tomato base, mozzarella and fresh basil.',          'image'=>'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&h=300&fit=crop',  'price'=>699,  'rating'=>5,'priority'=>1, 'status'=>1,'menu_category_id'=>$cats['pizzas']],
            ['title'=>'Pepperoni Pizza',           'slug'=>'pepperoni-pizza',           'description'=>'Generous pepperoni slices on rich tomato sauce.',           'image'=>'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400&h=300&fit=crop',  'price'=>799,  'rating'=>5,'priority'=>2, 'status'=>1,'menu_category_id'=>$cats['pizzas']],
            ['title'=>'BBQ Chicken Pizza',         'slug'=>'bbq-chicken-pizza',         'description'=>'Grilled chicken, BBQ sauce, red onion, mozzarella.',        'image'=>'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&h=300&fit=crop',  'price'=>849,  'rating'=>4,'priority'=>3, 'status'=>1,'menu_category_id'=>$cats['pizzas']],
            ['title'=>'Veg Supreme Pizza',         'slug'=>'veg-supreme-pizza',         'description'=>'Bell peppers, olives, mushrooms, onions & corn.',           'image'=>'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&h=300&fit=crop',  'price'=>749,  'rating'=>4,'priority'=>4, 'status'=>1,'menu_category_id'=>$cats['pizzas']],
            ['title'=>'Four Cheese Pizza',         'slug'=>'four-cheese-pizza',         'description'=>'Mozzarella, cheddar, parmesan and gorgonzola.',             'image'=>'https://images.unsplash.com/photo-1548369937-47519962c11a?w=400&h=300&fit=crop',  'price'=>899,  'rating'=>5,'priority'=>5, 'status'=>1,'menu_category_id'=>$cats['pizzas']],
            ['title'=>'Hawaiian Pizza',            'slug'=>'hawaiian-pizza',            'description'=>'Ham and pineapple on classic tomato base.',                 'image'=>'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&h=300&fit=crop',  'price'=>799,  'rating'=>3,'priority'=>6, 'status'=>1,'menu_category_id'=>$cats['pizzas']],
            ['title'=>'Meat Feast Pizza',          'slug'=>'meat-feast-pizza',          'description'=>'Pepperoni, sausage, ham, beef & mozzarella.',               'image'=>'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=400&h=300&fit=crop',  'price'=>949,  'rating'=>5,'priority'=>7, 'status'=>1,'menu_category_id'=>$cats['pizzas']],
            ['title'=>'Spicy Diavola Pizza',       'slug'=>'spicy-diavola-pizza',       'description'=>'Spicy salami, chilli flakes, tomato and mozzarella.',       'image'=>'https://images.unsplash.com/photo-1590947132387-155cc02f3212?w=400&h=300&fit=crop',  'price'=>849,  'rating'=>4,'priority'=>8, 'status'=>1,'menu_category_id'=>$cats['pizzas']],
            ['title'=>'Pesto Chicken Pizza',       'slug'=>'pesto-chicken-pizza',       'description'=>'Basil pesto base, grilled chicken, sun-dried tomatoes.',    'image'=>'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=400&h=300&fit=crop',  'price'=>849,  'rating'=>4,'priority'=>9, 'status'=>1,'menu_category_id'=>$cats['pizzas']],
            ['title'=>'Truffle Mushroom Pizza',    'slug'=>'truffle-mushroom-pizza',    'description'=>'Truffle oil, wild mushrooms, parmesan, rocket.',            'image'=>'https://images.unsplash.com/photo-1620374645498-af6bd681a0bd?w=400&h=300&fit=crop',  'price'=>999,  'rating'=>5,'priority'=>10,'status'=>1,'menu_category_id'=>$cats['pizzas']],

            ['title'=>'Spaghetti Bolognese',       'slug'=>'spaghetti-bolognese',       'description'=>'Slow-cooked beef ragù with spaghetti.',                    'image'=>'https://images.unsplash.com/photo-1622973536968-3ead9e780960?w=400&h=300&fit=crop',  'price'=>699,  'rating'=>5,'priority'=>1, 'status'=>1,'menu_category_id'=>$cats['pasta']],
            ['title'=>'Spaghetti Carbonara',       'slug'=>'spaghetti-carbonara',       'description'=>'Egg yolk, pancetta, parmesan & black pepper.',             'image'=>'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=400&h=300&fit=crop',  'price'=>749,  'rating'=>5,'priority'=>2, 'status'=>1,'menu_category_id'=>$cats['pasta']],
            ['title'=>'Penne Arrabbiata',          'slug'=>'penne-arrabbiata',          'description'=>'Spicy tomato sauce with garlic and chilli.',               'image'=>'https://images.unsplash.com/photo-1608756687911-aa1599ab3bd9?w=400&h=300&fit=crop',  'price'=>599,  'rating'=>4,'priority'=>3, 'status'=>1,'menu_category_id'=>$cats['pasta']],
            ['title'=>'Fettuccine Alfredo',        'slug'=>'fettuccine-alfredo',        'description'=>'Creamy butter-parmesan sauce with fettuccine.',            'image'=>'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?w=400&h=300&fit=crop',  'price'=>699,  'rating'=>4,'priority'=>4, 'status'=>1,'menu_category_id'=>$cats['pasta']],
            ['title'=>'Lasagna',                   'slug'=>'lasagna',                   'description'=>'Layered beef ragù, béchamel and pasta sheets.',            'image'=>'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=400&h=300&fit=crop',  'price'=>799,  'rating'=>5,'priority'=>5, 'status'=>1,'menu_category_id'=>$cats['pasta']],
            ['title'=>'Pesto Pasta',               'slug'=>'pesto-pasta',               'description'=>'Basil pesto, pine nuts, parmesan and penne.',              'image'=>'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=400&h=300&fit=crop',  'price'=>649,  'rating'=>4,'priority'=>6, 'status'=>1,'menu_category_id'=>$cats['pasta']],
            ['title'=>'Seafood Linguine',          'slug'=>'seafood-linguine',          'description'=>'Prawns, squid, mussels in white wine tomato sauce.',       'image'=>'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=400&h=300&fit=crop',  'price'=>899,  'rating'=>5,'priority'=>7, 'status'=>1,'menu_category_id'=>$cats['pasta']],
            ['title'=>'Mushroom Risotto',          'slug'=>'mushroom-risotto',          'description'=>'Creamy arborio rice with wild mushrooms & truffle oil.',   'image'=>'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=400&h=300&fit=crop',  'price'=>749,  'rating'=>4,'priority'=>8, 'status'=>1,'menu_category_id'=>$cats['pasta']],
            ['title'=>'Chicken Penne',             'slug'=>'chicken-penne',             'description'=>'Grilled chicken in creamy tomato penne.',                  'image'=>'https://images.unsplash.com/photo-1548365328-8c6db3220e4c?w=400&h=300&fit=crop',  'price'=>699,  'rating'=>4,'priority'=>9, 'status'=>1,'menu_category_id'=>$cats['pasta']],
            ['title'=>'Gnocchi Sorrentina',        'slug'=>'gnocchi-sorrentina',        'description'=>'Potato gnocchi with tomato, basil and mozzarella.',        'image'=>'https://images.unsplash.com/photo-1587740896339-96a76170508d?w=400&h=300&fit=crop',  'price'=>749,  'rating'=>4,'priority'=>10,'status'=>1,'menu_category_id'=>$cats['pasta']],

            ['title'=>'Caesar Salad',              'slug'=>'caesar-salad',              'description'=>'Romaine, croutons, parmesan, classic Caesar dressing.',    'image'=>'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop',  'price'=>499,  'rating'=>4,'priority'=>1, 'status'=>1,'menu_category_id'=>$cats['salads']],
            ['title'=>'Greek Salad',               'slug'=>'greek-salad',               'description'=>'Cucumber, tomato, olives, feta and oregano.',              'image'=>'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&h=300&fit=crop',  'price'=>449,  'rating'=>4,'priority'=>2, 'status'=>1,'menu_category_id'=>$cats['salads']],
            ['title'=>'Garden Fresh Salad',        'slug'=>'garden-fresh-salad',        'description'=>'Mixed greens, cherry tomatoes, cucumber, vinaigrette.',    'image'=>'https://images.unsplash.com/photo-1607532941433-304659e8198a?w=400&h=300&fit=crop',  'price'=>399,  'rating'=>3,'priority'=>3, 'status'=>1,'menu_category_id'=>$cats['salads']],
            ['title'=>'Chicken Avocado Salad',     'slug'=>'chicken-avocado-salad',     'description'=>'Grilled chicken, avocado, corn, lime dressing.',           'image'=>'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop',  'price'=>599,  'rating'=>5,'priority'=>4, 'status'=>1,'menu_category_id'=>$cats['salads']],
            ['title'=>'Nicoise Salad',             'slug'=>'nicoise-salad',             'description'=>'Tuna, egg, green beans, olives, Dijon dressing.',          'image'=>'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=400&h=300&fit=crop',  'price'=>549,  'rating'=>4,'priority'=>5, 'status'=>1,'menu_category_id'=>$cats['salads']],
            ['title'=>'Caprese Salad',             'slug'=>'caprese-salad',             'description'=>'Fresh mozzarella, tomato, basil and olive oil.',           'image'=>'https://images.unsplash.com/photo-1592417817098-8fd3d9eb14a5?w=400&h=300&fit=crop',  'price'=>499,  'rating'=>5,'priority'=>6, 'status'=>1,'menu_category_id'=>$cats['salads']],
            ['title'=>'Quinoa Salad',              'slug'=>'quinoa-salad',              'description'=>'Quinoa, chickpeas, roasted veggies, lemon tahini.',        'image'=>'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=400&h=300&fit=crop',  'price'=>549,  'rating'=>4,'priority'=>7, 'status'=>1,'menu_category_id'=>$cats['salads']],
            ['title'=>'Coleslaw',                  'slug'=>'coleslaw',                  'description'=>'Creamy shredded cabbage and carrot salad.',                'image'=>'https://images.unsplash.com/photo-1625944525533-473f1a3d54e7?w=400&h=300&fit=crop',  'price'=>249,  'rating'=>3,'priority'=>8, 'status'=>1,'menu_category_id'=>$cats['salads']],
            ['title'=>'Waldorf Salad',             'slug'=>'waldorf-salad',             'description'=>'Apple, celery, walnuts, grapes and mayo dressing.',        'image'=>'https://images.unsplash.com/photo-1574484284002-952d92456975?w=400&h=300&fit=crop',  'price'=>449,  'rating'=>3,'priority'=>9, 'status'=>1,'menu_category_id'=>$cats['salads']],
            ['title'=>'Prawn Salad',               'slug'=>'prawn-salad',               'description'=>'Chilled prawns, avocado, mango, citrus dressing.',         'image'=>'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400&h=300&fit=crop',  'price'=>649,  'rating'=>5,'priority'=>10,'status'=>1,'menu_category_id'=>$cats['salads']],

            ['title'=>'Club Sandwich',             'slug'=>'club-sandwich',             'description'=>'Triple-decker with chicken, bacon, egg & lettuce.',        'image'=>'https://images.unsplash.com/photo-1553909489-cd47e0907980?w=400&h=300&fit=crop',  'price'=>549,  'rating'=>4,'priority'=>1, 'status'=>1,'menu_category_id'=>$cats['sandwiches']],
            ['title'=>'BLT Sandwich',              'slug'=>'blt-sandwich',              'description'=>'Bacon, lettuce, tomato on toasted sourdough.',             'image'=>'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=400&h=300&fit=crop',  'price'=>449,  'rating'=>4,'priority'=>2, 'status'=>1,'menu_category_id'=>$cats['sandwiches']],
            ['title'=>'Grilled Cheese',            'slug'=>'grilled-cheese',            'description'=>'Buttery toasted bread with melted cheddar.',               'image'=>'https://images.unsplash.com/photo-1528736235302-52922df5c122?w=400&h=300&fit=crop',  'price'=>349,  'rating'=>4,'priority'=>3, 'status'=>1,'menu_category_id'=>$cats['sandwiches']],
            ['title'=>'Tuna Melt',                 'slug'=>'tuna-melt',                 'description'=>'Tuna mayo with melted cheese on toasted bread.',           'image'=>'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=400&h=300&fit=crop',  'price'=>499,  'rating'=>4,'priority'=>4, 'status'=>1,'menu_category_id'=>$cats['sandwiches']],
            ['title'=>'Chicken Caesar Wrap',       'slug'=>'chicken-caesar-wrap',       'description'=>'Grilled chicken, romaine, parmesan in a flour tortilla.',  'image'=>'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400&h=300&fit=crop',  'price'=>549,  'rating'=>5,'priority'=>5, 'status'=>1,'menu_category_id'=>$cats['sandwiches']],
            ['title'=>'Falafel Wrap',              'slug'=>'falafel-wrap',              'description'=>'Crispy falafel, hummus, salad in a flatbread.',            'image'=>'https://images.unsplash.com/photo-1590166969992-63a1db0c0fe0?w=400&h=300&fit=crop',  'price'=>499,  'rating'=>4,'priority'=>6, 'status'=>1,'menu_category_id'=>$cats['sandwiches']],
            ['title'=>'Beef Sub',                  'slug'=>'beef-sub',                  'description'=>'Sliced beef, caramelised onions, mustard on hoagie roll.', 'image'=>'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&h=300&fit=crop',  'price'=>599,  'rating'=>4,'priority'=>7, 'status'=>1,'menu_category_id'=>$cats['sandwiches']],
            ['title'=>'Veggie Panini',             'slug'=>'veggie-panini',             'description'=>'Grilled vegetables and pesto in pressed panini.',          'image'=>'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=300&fit=crop',  'price'=>449,  'rating'=>3,'priority'=>8, 'status'=>1,'menu_category_id'=>$cats['sandwiches']],
            ['title'=>'Egg & Cress Sandwich',      'slug'=>'egg-cress-sandwich',        'description'=>'Egg mayo and mustard cress on soft white bread.',          'image'=>'https://images.unsplash.com/photo-1554520735-0a6b8b6ce8b7?w=400&h=300&fit=crop',  'price'=>349,  'rating'=>3,'priority'=>9, 'status'=>1,'menu_category_id'=>$cats['sandwiches']],
            ['title'=>'Pulled Pork Sandwich',      'slug'=>'pulled-pork-sandwich',      'description'=>'Slow-cooked BBQ pulled pork with apple slaw.',             'image'=>'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=400&h=300&fit=crop',  'price'=>649,  'rating'=>5,'priority'=>10,'status'=>1,'menu_category_id'=>$cats['sandwiches']],

            ['title'=>'Tomato Basil Soup',         'slug'=>'tomato-basil-soup',         'description'=>'Velvety roasted tomato soup with fresh basil.',            'image'=>'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop',  'price'=>299,  'rating'=>4,'priority'=>1, 'status'=>1,'menu_category_id'=>$cats['soups']],
            ['title'=>'Cream of Mushroom Soup',    'slug'=>'cream-mushroom-soup',       'description'=>'Rich and creamy wild mushroom soup.',                      'image'=>'https://images.unsplash.com/photo-1603105037880-880cd4edfb0d?w=400&h=300&fit=crop',  'price'=>349,  'rating'=>5,'priority'=>2, 'status'=>1,'menu_category_id'=>$cats['soups']],
            ['title'=>'French Onion Soup',         'slug'=>'french-onion-soup',         'description'=>'Caramelised onion broth topped with gruyère crouton.',     'image'=>'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop',  'price'=>399,  'rating'=>5,'priority'=>3, 'status'=>1,'menu_category_id'=>$cats['soups']],
            ['title'=>'Chicken Noodle Soup',       'slug'=>'chicken-noodle-soup',       'description'=>'Classic chicken broth with noodles and vegetables.',       'image'=>'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=400&h=300&fit=crop',  'price'=>349,  'rating'=>4,'priority'=>4, 'status'=>1,'menu_category_id'=>$cats['soups']],
            ['title'=>'Lentil Soup',               'slug'=>'lentil-soup',               'description'=>'Spiced red lentil soup with lemon and cumin.',             'image'=>'https://images.unsplash.com/photo-1516684732162-798a0062be99?w=400&h=300&fit=crop',  'price'=>299,  'rating'=>4,'priority'=>5, 'status'=>1,'menu_category_id'=>$cats['soups']],
            ['title'=>'Pumpkin Soup',              'slug'=>'pumpkin-soup',              'description'=>'Roasted pumpkin soup with a swirl of cream.',              'image'=>'https://images.unsplash.com/photo-1574484284002-952d92456975?w=400&h=300&fit=crop',  'price'=>349,  'rating'=>4,'priority'=>6, 'status'=>1,'menu_category_id'=>$cats['soups']],
            ['title'=>'Minestrone',                'slug'=>'minestrone',                'description'=>'Hearty Italian vegetable and bean soup.',                  'image'=>'https://images.unsplash.com/photo-1555072956-7758afb20e8f?w=400&h=300&fit=crop',  'price'=>349,  'rating'=>4,'priority'=>7, 'status'=>1,'menu_category_id'=>$cats['soups']],
            ['title'=>'Broccoli Cheddar Soup',     'slug'=>'broccoli-cheddar-soup',     'description'=>'Creamy broccoli soup topped with cheddar.',                'image'=>'https://images.unsplash.com/photo-1582234372722-50d7ccc30ebd?w=400&h=300&fit=crop',  'price'=>349,  'rating'=>4,'priority'=>8, 'status'=>1,'menu_category_id'=>$cats['soups']],
            ['title'=>'Seafood Chowder',           'slug'=>'seafood-chowder',           'description'=>'Creamy chowder with fish, prawns and clams.',              'image'=>'https://images.unsplash.com/photo-1617093727343-374698b1b08d?w=400&h=300&fit=crop',  'price'=>449,  'rating'=>5,'priority'=>9, 'status'=>1,'menu_category_id'=>$cats['soups']],
            ['title'=>'Gazpacho',                  'slug'=>'gazpacho',                  'description'=>'Chilled Spanish tomato soup with cucumber and peppers.',   'image'=>'https://images.unsplash.com/photo-1611599537845-1c7aca0091c0?w=400&h=300&fit=crop',  'price'=>299,  'rating'=>3,'priority'=>10,'status'=>1,'menu_category_id'=>$cats['soups']],

            ['title'=>'Ribeye Steak',              'slug'=>'ribeye-steak',              'description'=>'300g aged ribeye with garlic butter and fries.',           'image'=>'https://images.unsplash.com/photo-1558030006-450675393462?w=400&h=300&fit=crop',  'price'=>1499, 'rating'=>5,'priority'=>1, 'status'=>1,'menu_category_id'=>$cats['grills']],
            ['title'=>'Grilled Chicken',           'slug'=>'grilled-chicken',           'description'=>'Herb-marinated chicken breast with grilled veggies.',      'image'=>'https://images.unsplash.com/photo-1432139509613-5c4255815697?w=400&h=300&fit=crop',  'price'=>799,  'rating'=>4,'priority'=>2, 'status'=>1,'menu_category_id'=>$cats['grills']],
            ['title'=>'BBQ Pork Ribs',             'slug'=>'bbq-pork-ribs',             'description'=>'Slow-smoked ribs glazed in BBQ sauce.',                   'image'=>'https://images.unsplash.com/photo-1544025162-d76694265947?w=400&h=300&fit=crop',  'price'=>1199, 'rating'=>5,'priority'=>3, 'status'=>1,'menu_category_id'=>$cats['grills']],
            ['title'=>'Lamb Chops',                'slug'=>'lamb-chops',                'description'=>'Rosemary-marinated lamb chops, mint jelly on the side.',   'image'=>'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=400&h=300&fit=crop',  'price'=>1299, 'rating'=>5,'priority'=>4, 'status'=>1,'menu_category_id'=>$cats['grills']],
            ['title'=>'Grilled Salmon',            'slug'=>'grilled-salmon',            'description'=>'Atlantic salmon with lemon butter and asparagus.',         'image'=>'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400&h=300&fit=crop',  'price'=>999,  'rating'=>5,'priority'=>5, 'status'=>1,'menu_category_id'=>$cats['grills']],
            ['title'=>'Chicken Skewers',           'slug'=>'chicken-skewers',           'description'=>'Marinated chicken kebab with tzatziki and pita.',          'image'=>'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=400&h=300&fit=crop',  'price'=>699,  'rating'=>4,'priority'=>6, 'status'=>1,'menu_category_id'=>$cats['grills']],
            ['title'=>'Mixed Grill Platter',       'slug'=>'mixed-grill-platter',       'description'=>'Ribs, chicken, sausage, lamb chop — the works.',           'image'=>'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&h=300&fit=crop',  'price'=>1799, 'rating'=>5,'priority'=>7, 'status'=>1,'menu_category_id'=>$cats['grills']],
            ['title'=>'Grilled Prawns',            'slug'=>'grilled-prawns',            'description'=>'Jumbo prawns grilled in garlic and herb butter.',          'image'=>'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&h=300&fit=crop',  'price'=>999,  'rating'=>4,'priority'=>8, 'status'=>1,'menu_category_id'=>$cats['grills']],
            ['title'=>'T-Bone Steak',              'slug'=>'t-bone-steak',              'description'=>'Impressive T-bone cooked to your preference.',             'image'=>'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=400&h=300&fit=crop',  'price'=>1699, 'rating'=>5,'priority'=>9, 'status'=>1,'menu_category_id'=>$cats['grills']],
            ['title'=>'Corn on the Cob',           'slug'=>'corn-on-the-cob',           'description'=>'Charred corn with chilli butter and lime.',                'image'=>'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400&h=300&fit=crop',  'price'=>249,  'rating'=>3,'priority'=>10,'status'=>1,'menu_category_id'=>$cats['grills']],

            ['title'=>'Chocolate Lava Cake',       'slug'=>'chocolate-lava-cake',       'description'=>'Warm chocolate cake with a molten centre.',                'image'=>'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&h=300&fit=crop',  'price'=>499,  'rating'=>5,'priority'=>1, 'status'=>1,'menu_category_id'=>$cats['desserts']],
            ['title'=>'New York Cheesecake',       'slug'=>'new-york-cheesecake',       'description'=>'Classic baked cheesecake with berry compote.',             'image'=>'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=400&h=300&fit=crop',  'price'=>449,  'rating'=>5,'priority'=>2, 'status'=>1,'menu_category_id'=>$cats['desserts']],
            ['title'=>'Tiramisu',                  'slug'=>'tiramisu',                  'description'=>'Coffee-soaked ladyfingers with mascarpone cream.',         'image'=>'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&h=300&fit=crop',  'price'=>449,  'rating'=>5,'priority'=>3, 'status'=>1,'menu_category_id'=>$cats['desserts']],
            ['title'=>'Crème Brûlée',              'slug'=>'creme-brulee',              'description'=>'Silky vanilla custard with caramelised sugar top.',        'image'=>'https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?w=400&h=300&fit=crop',  'price'=>399,  'rating'=>5,'priority'=>4, 'status'=>1,'menu_category_id'=>$cats['desserts']],
            ['title'=>'Brownie & Ice Cream',       'slug'=>'brownie-ice-cream',         'description'=>'Fudgy brownie served warm with vanilla ice cream.',        'image'=>'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=400&h=300&fit=crop',  'price'=>399,  'rating'=>4,'priority'=>5, 'status'=>1,'menu_category_id'=>$cats['desserts']],
            ['title'=>'Waffles',                   'slug'=>'waffles',                   'description'=>'Belgian waffles with whipped cream and maple syrup.',      'image'=>'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400&h=300&fit=crop',  'price'=>449,  'rating'=>4,'priority'=>6, 'status'=>1,'menu_category_id'=>$cats['desserts']],
            ['title'=>'Panna Cotta',               'slug'=>'panna-cotta',               'description'=>'Vanilla panna cotta with raspberry coulis.',               'image'=>'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=300&fit=crop',  'price'=>349,  'rating'=>4,'priority'=>7, 'status'=>1,'menu_category_id'=>$cats['desserts']],
            ['title'=>'Apple Crumble',             'slug'=>'apple-crumble',             'description'=>'Spiced apple baked under an oat crumble topping.',         'image'=>'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400&h=300&fit=crop',  'price'=>399,  'rating'=>4,'priority'=>8, 'status'=>1,'menu_category_id'=>$cats['desserts']],
            ['title'=>'Ice Cream Sundae',          'slug'=>'ice-cream-sundae',          'description'=>'Three scoops, chocolate sauce, nuts and cherry.',          'image'=>'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&h=300&fit=crop',  'price'=>349,  'rating'=>4,'priority'=>9, 'status'=>1,'menu_category_id'=>$cats['desserts']],
            ['title'=>'Sticky Toffee Pudding',     'slug'=>'sticky-toffee-pudding',     'description'=>'Moist date sponge drenched in toffee sauce.',             'image'=>'https://images.unsplash.com/photo-1541599540903-216a46ca1dc0?w=400&h=300&fit=crop',  'price'=>399,  'rating'=>5,'priority'=>10,'status'=>1,'menu_category_id'=>$cats['desserts']],

            ['title'=>'Espresso',                  'slug'=>'espresso',                  'description'=>'Single shot of rich, concentrated espresso.',              'image'=>'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=400&h=300&fit=crop',  'price'=>199,  'rating'=>4,'priority'=>1, 'status'=>1,'menu_category_id'=>$cats['hot-drinks']],
            ['title'=>'Cappuccino',                'slug'=>'cappuccino',                'description'=>'Espresso with steamed milk and thick foam.',               'image'=>'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=400&h=300&fit=crop',  'price'=>299,  'rating'=>5,'priority'=>2, 'status'=>1,'menu_category_id'=>$cats['hot-drinks']],
            ['title'=>'Latte',                     'slug'=>'latte',                     'description'=>'Smooth espresso with steamed milk, light foam.',           'image'=>'https://images.unsplash.com/photo-1561047029-3000c68339ca?w=400&h=300&fit=crop',  'price'=>299,  'rating'=>5,'priority'=>3, 'status'=>1,'menu_category_id'=>$cats['hot-drinks']],
            ['title'=>'Flat White',                'slug'=>'flat-white',                'description'=>'Double ristretto with velvety microfoam milk.',            'image'=>'https://images.unsplash.com/photo-1577968897966-3d4325b36b61?w=400&h=300&fit=crop',  'price'=>299,  'rating'=>5,'priority'=>4, 'status'=>1,'menu_category_id'=>$cats['hot-drinks']],
            ['title'=>'Hot Chocolate',             'slug'=>'hot-chocolate',             'description'=>'Creamy Belgian hot chocolate topped with cream.',          'image'=>'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?w=400&h=300&fit=crop',  'price'=>299,  'rating'=>5,'priority'=>5, 'status'=>1,'menu_category_id'=>$cats['hot-drinks']],
            ['title'=>'English Breakfast Tea',     'slug'=>'english-breakfast-tea',     'description'=>'Classic black tea served with milk.',                      'image'=>'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=300&fit=crop',  'price'=>199,  'rating'=>4,'priority'=>6, 'status'=>1,'menu_category_id'=>$cats['hot-drinks']],
            ['title'=>'Green Tea',                 'slug'=>'green-tea',                 'description'=>'Premium Japanese green tea, light and refreshing.',        'image'=>'https://images.unsplash.com/photo-1627435601361-ec25f5b1d0e5?w=400&h=300&fit=crop',  'price'=>199,  'rating'=>4,'priority'=>7, 'status'=>1,'menu_category_id'=>$cats['hot-drinks']],
            ['title'=>'Chai Latte',                'slug'=>'chai-latte',                'description'=>'Spiced chai concentrate with steamed oat milk.',           'image'=>'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=400&h=300&fit=crop',  'price'=>299,  'rating'=>4,'priority'=>8, 'status'=>1,'menu_category_id'=>$cats['hot-drinks']],
            ['title'=>'Mocha',                     'slug'=>'mocha',                     'description'=>'Espresso, chocolate sauce and steamed milk.',              'image'=>'https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?w=400&h=300&fit=crop',  'price'=>329,  'rating'=>5,'priority'=>9, 'status'=>1,'menu_category_id'=>$cats['hot-drinks']],
            ['title'=>'Americano',                 'slug'=>'americano',                 'description'=>'Double espresso topped with hot water.',                   'image'=>'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=400&h=300&fit=crop',  'price'=>249,  'rating'=>4,'priority'=>10,'status'=>1,'menu_category_id'=>$cats['hot-drinks']],

            ['title'=>'Fresh Orange Juice',        'slug'=>'fresh-orange-juice',        'description'=>'Freshly squeezed orange juice, served chilled.',           'image'=>'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&h=300&fit=crop',  'price'=>279,  'rating'=>4,'priority'=>1, 'status'=>1,'menu_category_id'=>$cats['cold-drinks']],
            ['title'=>'Mango Lassi',               'slug'=>'mango-lassi',               'description'=>'Chilled mango and yoghurt drink with a hint of cardamom.', 'image'=>'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=400&h=300&fit=crop',  'price'=>299,  'rating'=>5,'priority'=>2, 'status'=>1,'menu_category_id'=>$cats['cold-drinks']],
            ['title'=>'Strawberry Milkshake',      'slug'=>'strawberry-milkshake',      'description'=>'Thick strawberry milkshake with whipped cream.',           'image'=>'https://images.unsplash.com/photo-1568901839119-631418a3910d?w=400&h=300&fit=crop',  'price'=>349,  'rating'=>5,'priority'=>3, 'status'=>1,'menu_category_id'=>$cats['cold-drinks']],
            ['title'=>'Iced Latte',                'slug'=>'iced-latte',                'description'=>'Cold brew espresso over ice with chilled milk.',           'image'=>'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=400&h=300&fit=crop',  'price'=>329,  'rating'=>5,'priority'=>4, 'status'=>1,'menu_category_id'=>$cats['cold-drinks']],
            ['title'=>'Watermelon Juice',          'slug'=>'watermelon-juice',          'description'=>'Fresh watermelon blended and served over ice.',            'image'=>'https://images.unsplash.com/photo-1534706936160-d5ee67737249?w=400&h=300&fit=crop',  'price'=>249,  'rating'=>4,'priority'=>5, 'status'=>1,'menu_category_id'=>$cats['cold-drinks']],
            ['title'=>'Lemonade',                  'slug'=>'lemonade',                  'description'=>'Classic homemade lemonade, sweet and tangy.',              'image'=>'https://images.unsplash.com/photo-1523677011781-c91d1bbe2f9e?w=400&h=300&fit=crop',  'price'=>229,  'rating'=>4,'priority'=>6, 'status'=>1,'menu_category_id'=>$cats['cold-drinks']],
            ['title'=>'Iced Tea',                  'slug'=>'iced-tea',                  'description'=>'Cold-brewed black tea with lemon and mint.',               'image'=>'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=300&fit=crop',  'price'=>229,  'rating'=>4,'priority'=>7, 'status'=>1,'menu_category_id'=>$cats['cold-drinks']],
            ['title'=>'Coconut Water',             'slug'=>'coconut-water',             'description'=>'Pure natural coconut water, hydrating and light.',         'image'=>'https://images.unsplash.com/photo-1550259979-ed79b48d2a30?w=400&h=300&fit=crop',  'price'=>249,  'rating'=>4,'priority'=>8, 'status'=>1,'menu_category_id'=>$cats['cold-drinks']],
            ['title'=>'Berry Smoothie',            'slug'=>'berry-smoothie',            'description'=>'Mixed berry, banana and almond milk smoothie.',            'image'=>'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=400&h=300&fit=crop',  'price'=>349,  'rating'=>5,'priority'=>9, 'status'=>1,'menu_category_id'=>$cats['cold-drinks']],
            ['title'=>'Virgin Mojito',             'slug'=>'virgin-mojito',             'description'=>'Lime, mint, sugar syrup and soda water over ice.',         'image'=>'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400&h=300&fit=crop',  'price'=>279,  'rating'=>5,'priority'=>10,'status'=>1,'menu_category_id'=>$cats['cold-drinks']],
        ];

        foreach ($menus as $menu) {
            Menu::firstOrCreate(['slug' => $menu['slug']], $menu);
        }
    }
}